Search.appendIndex(
    [
                {
            "fqsen": "\\Twitch\\Http\\DriverInterface",
            "name": "DriverInterface",
            "summary": "Executes\u0020a\u0020single\u0020prepared\u0020\u007B\u0040see\u0020Request\u007D\u0020and\u0020resolves\u0020with\u0020the\u0020raw\n\u007B\u0040see\u0020ResponseInterface\u007D\u0020\u2014\u0020success\u0020or\u0020error\u0020status\u0020alike.\u0020Retry,\u0020rate\u002Dlimit,\nand\u0020exception\u0020mapping\u0020are\u0020\u007B\u0040see\u0020Http\u007D\u0027s\u0020job,\u0020not\u0020the\u0020driver\u0027s.",
            "url": "classes/Twitch-Http-DriverInterface.html"
        },                {
            "fqsen": "\\Twitch\\Http\\DriverInterface\u003A\u003ArunRequest\u0028\u0029",
            "name": "runRequest",
            "summary": "",
            "url": "classes/Twitch-Http-DriverInterface.html#method_runRequest"
        },                {
            "fqsen": "\\Twitch\\Http\\Drivers\\React",
            "name": "React",
            "summary": "The\u0020default\u0020\u007B\u0040see\u0020DriverInterface\u007D\u003A\u0020a\u0020non\u002Dblocking\u0020\u007B\u0040see\u0020Browser\u007D\u0020from\n\u0060react\/http\u0060.\u0020Configured\u0020to\u0020surface\u00204xx\/5xx\u0020as\u0020resolved\u0020responses\u0020\u0028not\nrejections\u0029\u0020so\u0020\u007B\u0040see\u0020\\Twitch\\Http\\Http\u007D\u0020can\u0020map\u0020them\u0020to\u0020typed\u0020exceptions\u0020and\nretry\u0020where\u0020appropriate.",
            "url": "classes/Twitch-Http-Drivers-React.html"
        },                {
            "fqsen": "\\Twitch\\Http\\Drivers\\React\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Twitch-Http-Drivers-React.html#method___construct"
        },                {
            "fqsen": "\\Twitch\\Http\\Drivers\\React\u003A\u003ArunRequest\u0028\u0029",
            "name": "runRequest",
            "summary": "",
            "url": "classes/Twitch-Http-Drivers-React.html#method_runRequest"
        },                {
            "fqsen": "\\Twitch\\Http\\Drivers\\React\u003A\u003A\u0024browser",
            "name": "browser",
            "summary": "",
            "url": "classes/Twitch-Http-Drivers-React.html#property_browser"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint",
            "name": "Endpoint",
            "summary": "The\u0020set\u0020of\u0020Twitch\u0020Helix\u0020endpoints,\u0020relative\u0020to\u0020\u007B\u0040see\u0020Http\u003A\u003ABASE_URL\u007D.",
            "url": "classes/Twitch-Http-Endpoint.html"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#method___construct"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003Abind\u0028\u0029",
            "name": "bind",
            "summary": "Creates\u0020an\u0020endpoint\u0020and\u0020binds\u0020positional\u0020path\u0020arguments\u0020to\u0020it.",
            "url": "classes/Twitch-Http-Endpoint.html#method_bind"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AbindArgs\u0028\u0029",
            "name": "bindArgs",
            "summary": "Binds\u0020positional\u0020path\u0020arguments,\u0020in\u0020the\u0020order\u0020the\u0020\u0060\u003Aparams\u0060\u0020appear.",
            "url": "classes/Twitch-Http-Endpoint.html#method_bindArgs"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AbindAssoc\u0028\u0029",
            "name": "bindAssoc",
            "summary": "Binds\u0020path\u0020arguments\u0020by\u0020name.",
            "url": "classes/Twitch-Http-Endpoint.html#method_bindAssoc"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AaddQuery\u0028\u0029",
            "name": "addQuery",
            "summary": "Adds\u0020one\u0020query\u002Dstring\u0020pair.\u0020Arrays\u0020are\u0020repeated\u0020\u0028\u0060\u003Fid\u003D1\u0026id\u003D2\u0060\u0029.",
            "url": "classes/Twitch-Http-Endpoint.html#method_addQuery"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AwithQuery\u0028\u0029",
            "name": "withQuery",
            "summary": "Merges\u0020an\u0020associative\u0020array\u0020of\u0020query\u0020pairs,\u0020skipping\u0020null\u0020values.",
            "url": "classes/Twitch-Http-Endpoint.html#method_withQuery"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AgetQuery\u0028\u0029",
            "name": "getQuery",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#method_getQuery"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AtoAbsoluteEndpoint\u0028\u0029",
            "name": "toAbsoluteEndpoint",
            "summary": "Renders\u0020the\u0020endpoint\u0020with\u0020path\u0020params\u0020substituted\u0020and\u0020the\u0020query\u0020string\nappended.\u0020Twitch\u0020repeats\u0020array\u0020params\u0020rather\u0020than\u0020using\u0020\u0060key\u005B\u005D\u0060.",
            "url": "classes/Twitch-Http-Endpoint.html#method_toAbsoluteEndpoint"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AbuildQuery\u0028\u0029",
            "name": "buildQuery",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#method_buildQuery"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#method___toString"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ACOMMERCIAL",
            "name": "COMMERCIAL",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_COMMERCIAL"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AAD_SCHEDULE",
            "name": "AD_SCHEDULE",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_AD_SCHEDULE"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AAD_SNOOZE",
            "name": "AD_SNOOZE",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_AD_SNOOZE"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AEXTENSION_ANALYTICS",
            "name": "EXTENSION_ANALYTICS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_EXTENSION_ANALYTICS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AGAME_ANALYTICS",
            "name": "GAME_ANALYTICS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_GAME_ANALYTICS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ABITS_LEADERBOARD",
            "name": "BITS_LEADERBOARD",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_BITS_LEADERBOARD"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ACHEERMOTES",
            "name": "CHEERMOTES",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_CHEERMOTES"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AEXTENSION_TRANSACTIONS",
            "name": "EXTENSION_TRANSACTIONS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_EXTENSION_TRANSACTIONS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ACHANNELS",
            "name": "CHANNELS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_CHANNELS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ACHANNEL_EDITORS",
            "name": "CHANNEL_EDITORS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_CHANNEL_EDITORS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ACHANNELS_FOLLOWED",
            "name": "CHANNELS_FOLLOWED",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_CHANNELS_FOLLOWED"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ACHANNEL_FOLLOWERS",
            "name": "CHANNEL_FOLLOWERS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_CHANNEL_FOLLOWERS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ACUSTOM_REWARDS",
            "name": "CUSTOM_REWARDS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_CUSTOM_REWARDS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ACUSTOM_REWARD_REDEMPTIONS",
            "name": "CUSTOM_REWARD_REDEMPTIONS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_CUSTOM_REWARD_REDEMPTIONS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ACHARITY_CAMPAIGN",
            "name": "CHARITY_CAMPAIGN",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_CHARITY_CAMPAIGN"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ACHARITY_DONATIONS",
            "name": "CHARITY_DONATIONS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_CHARITY_DONATIONS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ACHATTERS",
            "name": "CHATTERS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_CHATTERS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ACHANNEL_EMOTES",
            "name": "CHANNEL_EMOTES",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_CHANNEL_EMOTES"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AGLOBAL_EMOTES",
            "name": "GLOBAL_EMOTES",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_GLOBAL_EMOTES"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AEMOTE_SETS",
            "name": "EMOTE_SETS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_EMOTE_SETS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AUSER_EMOTES",
            "name": "USER_EMOTES",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_USER_EMOTES"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ACHANNEL_CHAT_BADGES",
            "name": "CHANNEL_CHAT_BADGES",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_CHANNEL_CHAT_BADGES"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AGLOBAL_CHAT_BADGES",
            "name": "GLOBAL_CHAT_BADGES",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_GLOBAL_CHAT_BADGES"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ACHAT_SETTINGS",
            "name": "CHAT_SETTINGS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_CHAT_SETTINGS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ASHARED_CHAT_SESSION",
            "name": "SHARED_CHAT_SESSION",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_SHARED_CHAT_SESSION"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ACHAT_ANNOUNCEMENTS",
            "name": "CHAT_ANNOUNCEMENTS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_CHAT_ANNOUNCEMENTS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ASHOUTOUTS",
            "name": "SHOUTOUTS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_SHOUTOUTS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ASEND_CHAT_MESSAGE",
            "name": "SEND_CHAT_MESSAGE",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_SEND_CHAT_MESSAGE"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AUSER_CHAT_COLOR",
            "name": "USER_CHAT_COLOR",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_USER_CHAT_COLOR"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ACLIPS",
            "name": "CLIPS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_CLIPS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ACCLS",
            "name": "CCLS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_CCLS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ACONDUITS",
            "name": "CONDUITS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_CONDUITS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ACONDUIT_SHARDS",
            "name": "CONDUIT_SHARDS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_CONDUIT_SHARDS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ADROPS_ENTITLEMENTS",
            "name": "DROPS_ENTITLEMENTS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_DROPS_ENTITLEMENTS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AEVENTSUB_SUBSCRIPTIONS",
            "name": "EVENTSUB_SUBSCRIPTIONS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_EVENTSUB_SUBSCRIPTIONS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AEXTENSION_CONFIGURATION",
            "name": "EXTENSION_CONFIGURATION",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_EXTENSION_CONFIGURATION"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AEXTENSION_REQUIRED_CONFIG",
            "name": "EXTENSION_REQUIRED_CONFIG",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_EXTENSION_REQUIRED_CONFIG"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AEXTENSION_PUBSUB_MESSAGE",
            "name": "EXTENSION_PUBSUB_MESSAGE",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_EXTENSION_PUBSUB_MESSAGE"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AEXTENSION_LIVE_CHANNELS",
            "name": "EXTENSION_LIVE_CHANNELS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_EXTENSION_LIVE_CHANNELS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AEXTENSION_SECRETS",
            "name": "EXTENSION_SECRETS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_EXTENSION_SECRETS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AEXTENSION_CHAT_MESSAGE",
            "name": "EXTENSION_CHAT_MESSAGE",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_EXTENSION_CHAT_MESSAGE"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AEXTENSIONS",
            "name": "EXTENSIONS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_EXTENSIONS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ARELEASED_EXTENSIONS",
            "name": "RELEASED_EXTENSIONS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_RELEASED_EXTENSIONS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AEXTENSION_BITS_PRODUCTS",
            "name": "EXTENSION_BITS_PRODUCTS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_EXTENSION_BITS_PRODUCTS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ATOP_GAMES",
            "name": "TOP_GAMES",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_TOP_GAMES"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AGAMES",
            "name": "GAMES",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_GAMES"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AGOALS",
            "name": "GOALS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_GOALS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AGUEST_STAR_CHANNEL_SETTINGS",
            "name": "GUEST_STAR_CHANNEL_SETTINGS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_GUEST_STAR_CHANNEL_SETTINGS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AGUEST_STAR_SESSION",
            "name": "GUEST_STAR_SESSION",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_GUEST_STAR_SESSION"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AGUEST_STAR_INVITES",
            "name": "GUEST_STAR_INVITES",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_GUEST_STAR_INVITES"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AGUEST_STAR_SLOT",
            "name": "GUEST_STAR_SLOT",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_GUEST_STAR_SLOT"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AGUEST_STAR_SLOT_SETTINGS",
            "name": "GUEST_STAR_SLOT_SETTINGS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_GUEST_STAR_SLOT_SETTINGS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AHYPE_TRAIN_EVENTS",
            "name": "HYPE_TRAIN_EVENTS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_HYPE_TRAIN_EVENTS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AAUTOMOD_STATUS",
            "name": "AUTOMOD_STATUS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_AUTOMOD_STATUS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AAUTOMOD_HELD_MESSAGE",
            "name": "AUTOMOD_HELD_MESSAGE",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_AUTOMOD_HELD_MESSAGE"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AAUTOMOD_SETTINGS",
            "name": "AUTOMOD_SETTINGS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_AUTOMOD_SETTINGS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ABANNED_USERS",
            "name": "BANNED_USERS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_BANNED_USERS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ABANS",
            "name": "BANS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_BANS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AUNBAN_REQUESTS",
            "name": "UNBAN_REQUESTS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_UNBAN_REQUESTS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ABLOCKED_TERMS",
            "name": "BLOCKED_TERMS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_BLOCKED_TERMS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AMODERATION_CHAT",
            "name": "MODERATION_CHAT",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_MODERATION_CHAT"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AMODERATED_CHANNELS",
            "name": "MODERATED_CHANNELS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_MODERATED_CHANNELS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AMODERATORS",
            "name": "MODERATORS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_MODERATORS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ACHANNEL_VIPS",
            "name": "CHANNEL_VIPS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_CHANNEL_VIPS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ASHIELD_MODE",
            "name": "SHIELD_MODE",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_SHIELD_MODE"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AWARNINGS",
            "name": "WARNINGS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_WARNINGS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003APOLLS",
            "name": "POLLS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_POLLS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003APREDICTIONS",
            "name": "PREDICTIONS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_PREDICTIONS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ARAIDS",
            "name": "RAIDS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_RAIDS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ASCHEDULE",
            "name": "SCHEDULE",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_SCHEDULE"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ASCHEDULE_ICALENDAR",
            "name": "SCHEDULE_ICALENDAR",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_SCHEDULE_ICALENDAR"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ASCHEDULE_SETTINGS",
            "name": "SCHEDULE_SETTINGS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_SCHEDULE_SETTINGS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ASCHEDULE_SEGMENT",
            "name": "SCHEDULE_SEGMENT",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_SCHEDULE_SEGMENT"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ASEARCH_CATEGORIES",
            "name": "SEARCH_CATEGORIES",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_SEARCH_CATEGORIES"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ASEARCH_CHANNELS",
            "name": "SEARCH_CHANNELS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_SEARCH_CHANNELS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ASTREAM_KEY",
            "name": "STREAM_KEY",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_STREAM_KEY"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ASTREAMS",
            "name": "STREAMS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_STREAMS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ASTREAMS_FOLLOWED",
            "name": "STREAMS_FOLLOWED",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_STREAMS_FOLLOWED"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ASTREAM_MARKERS",
            "name": "STREAM_MARKERS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_STREAM_MARKERS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ASTREAM_TAGS",
            "name": "STREAM_TAGS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_STREAM_TAGS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ASUBSCRIPTIONS",
            "name": "SUBSCRIPTIONS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_SUBSCRIPTIONS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ASUBSCRIPTION_USER",
            "name": "SUBSCRIPTION_USER",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_SUBSCRIPTION_USER"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AALL_STREAM_TAGS",
            "name": "ALL_STREAM_TAGS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_ALL_STREAM_TAGS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ACHANNEL_TEAMS",
            "name": "CHANNEL_TEAMS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_CHANNEL_TEAMS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003ATEAMS",
            "name": "TEAMS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_TEAMS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AUSERS",
            "name": "USERS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_USERS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AUSER_BLOCKS",
            "name": "USER_BLOCKS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_USER_BLOCKS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AUSER_EXTENSIONS_LIST",
            "name": "USER_EXTENSIONS_LIST",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_USER_EXTENSIONS_LIST"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AUSER_EXTENSIONS",
            "name": "USER_EXTENSIONS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_USER_EXTENSIONS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AVIDEOS",
            "name": "VIDEOS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_VIDEOS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AWHISPERS",
            "name": "WHISPERS",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#constant_WHISPERS"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003AREGEX",
            "name": "REGEX",
            "summary": "Regex\u0020identifying\u0020\u0060\u003Aparam\u0060\u0020placeholders\u0020in\u0020an\u0020endpoint.",
            "url": "classes/Twitch-Http-Endpoint.html#constant_REGEX"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003A\u0024endpoint",
            "name": "endpoint",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#property_endpoint"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003A\u0024vars",
            "name": "vars",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#property_vars"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003A\u0024args",
            "name": "args",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#property_args"
        },                {
            "fqsen": "\\Twitch\\Http\\Endpoint\u003A\u003A\u0024query",
            "name": "query",
            "summary": "",
            "url": "classes/Twitch-Http-Endpoint.html#property_query"
        },                {
            "fqsen": "\\Twitch\\Http\\Exceptions\\BadRequestException",
            "name": "BadRequestException",
            "summary": "The\u0020request\u0020was\u0020malformed\u0020or\u0020missing\u0020a\u0020required\u0020parameter.",
            "url": "classes/Twitch-Http-Exceptions-BadRequestException.html"
        },                {
            "fqsen": "\\Twitch\\Http\\Exceptions\\ConflictException",
            "name": "ConflictException",
            "summary": "The\u0020request\u0020conflicts\u0020with\u0020the\u0020current\u0020state\u0020of\u0020the\u0020resource.",
            "url": "classes/Twitch-Http-Exceptions-ConflictException.html"
        },                {
            "fqsen": "\\Twitch\\Http\\Exceptions\\HttpException",
            "name": "HttpException",
            "summary": "Base\u0020class\u0020for\u0020every\u0020error\u0020surfaced\u0020by\u0020\u007B\u0040see\u0020\\Twitch\\Http\\Http\u007D.",
            "url": "classes/Twitch-Http-Exceptions-HttpException.html"
        },                {
            "fqsen": "\\Twitch\\Http\\Exceptions\\HttpException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Twitch-Http-Exceptions-HttpException.html#method___construct"
        },                {
            "fqsen": "\\Twitch\\Http\\Exceptions\\HttpException\u003A\u003AfromResponse\u0028\u0029",
            "name": "fromResponse",
            "summary": "Builds\u0020the\u0020right\u0020exception\u0020subclass\u0020for\u0020a\u0020failed\u0020response.",
            "url": "classes/Twitch-Http-Exceptions-HttpException.html#method_fromResponse"
        },                {
            "fqsen": "\\Twitch\\Http\\Exceptions\\HttpException\u003A\u003A\u0024status",
            "name": "status",
            "summary": "",
            "url": "classes/Twitch-Http-Exceptions-HttpException.html#property_status"
        },                {
            "fqsen": "\\Twitch\\Http\\Exceptions\\HttpException\u003A\u003A\u0024error",
            "name": "error",
            "summary": "",
            "url": "classes/Twitch-Http-Exceptions-HttpException.html#property_error"
        },                {
            "fqsen": "\\Twitch\\Http\\Exceptions\\HttpException\u003A\u003A\u0024response",
            "name": "response",
            "summary": "",
            "url": "classes/Twitch-Http-Exceptions-HttpException.html#property_response"
        },                {
            "fqsen": "\\Twitch\\Http\\Exceptions\\InvalidTokenException",
            "name": "InvalidTokenException",
            "summary": "The\u0020OAuth\u0020token\u0020is\u0020missing,\u0020invalid,\u0020or\u0020expired.",
            "url": "classes/Twitch-Http-Exceptions-InvalidTokenException.html"
        },                {
            "fqsen": "\\Twitch\\Http\\Exceptions\\MethodNotAllowedException",
            "name": "MethodNotAllowedException",
            "summary": "The\u0020HTTP\u0020method\u0020is\u0020not\u0020allowed\u0020on\u0020this\u0020endpoint.",
            "url": "classes/Twitch-Http-Exceptions-MethodNotAllowedException.html"
        },                {
            "fqsen": "\\Twitch\\Http\\Exceptions\\NoPermissionsException",
            "name": "NoPermissionsException",
            "summary": "The\u0020token\u0020lacks\u0020the\u0020scope\u0020required\u0020for\u0020this\u0020request.",
            "url": "classes/Twitch-Http-Exceptions-NoPermissionsException.html"
        },                {
            "fqsen": "\\Twitch\\Http\\Exceptions\\NotFoundException",
            "name": "NotFoundException",
            "summary": "The\u0020requested\u0020resource\u0020does\u0020not\u0020exist.",
            "url": "classes/Twitch-Http-Exceptions-NotFoundException.html"
        },                {
            "fqsen": "\\Twitch\\Http\\Exceptions\\RateLimitException",
            "name": "RateLimitException",
            "summary": "The\u0020application\u0020has\u0020exceeded\u0020its\u0020Twitch\u0020rate\u002Dlimit\u0020bucket.",
            "url": "classes/Twitch-Http-Exceptions-RateLimitException.html"
        },                {
            "fqsen": "\\Twitch\\Http\\Exceptions\\ServerException",
            "name": "ServerException",
            "summary": "Twitch\u0020returned\u0020a\u00205xx\u0020error.",
            "url": "classes/Twitch-Http-Exceptions-ServerException.html"
        },                {
            "fqsen": "\\Twitch\\Http\\Exceptions\\UnprocessableException",
            "name": "UnprocessableException",
            "summary": "The\u0020request\u0020was\u0020well\u002Dformed\u0020but\u0020semantically\u0020invalid.",
            "url": "classes/Twitch-Http-Exceptions-UnprocessableException.html"
        },                {
            "fqsen": "\\Twitch\\Http\\Http",
            "name": "Http",
            "summary": "Non\u002Dblocking\u0020HTTP\u0020client\u0020for\u0020the\u0020Twitch\u0020Helix\u0020API.",
            "url": "classes/Twitch-Http-Http.html"
        },                {
            "fqsen": "\\Twitch\\Http\\Http\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Twitch-Http-Http.html#method___construct"
        },                {
            "fqsen": "\\Twitch\\Http\\Http\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Convenience\u0020constructor\u0020that\u0020wires\u0020the\u0020default\u0020ReactPHP\u0020driver\u0020against\u0020the\nshared\u0020event\u0020loop.",
            "url": "classes/Twitch-Http-Http.html#method_create"
        },                {
            "fqsen": "\\Twitch\\Http\\Http\u003A\u003AsetDriver\u0028\u0029",
            "name": "setDriver",
            "summary": "",
            "url": "classes/Twitch-Http-Http.html#method_setDriver"
        },                {
            "fqsen": "\\Twitch\\Http\\Http\u003A\u003AsetToken\u0028\u0029",
            "name": "setToken",
            "summary": "Swap\u0020in\u0020a\u0020fresh\u0020OAuth\u0020token\u0020\u0028e.g.\u0020after\u0020a\u0020refresh\u0029.\u0020Queued\u0020requests\u0020pick\u0020it\u0020up.",
            "url": "classes/Twitch-Http-Http.html#method_setToken"
        },                {
            "fqsen": "\\Twitch\\Http\\Http\u003A\u003AgetRateLimit\u0028\u0029",
            "name": "getRateLimit",
            "summary": "The\u0020most\u0020recent\u0020rate\u002Dlimit\u0020bucket\u0020snapshot,\u0020if\u0020any\u0020request\u0020has\u0020completed.",
            "url": "classes/Twitch-Http-Http.html#method_getRateLimit"
        },                {
            "fqsen": "\\Twitch\\Http\\Http\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/Twitch-Http-Http.html#method_get"
        },                {
            "fqsen": "\\Twitch\\Http\\Http\u003A\u003Apost\u0028\u0029",
            "name": "post",
            "summary": "",
            "url": "classes/Twitch-Http-Http.html#method_post"
        },                {
            "fqsen": "\\Twitch\\Http\\Http\u003A\u003Aput\u0028\u0029",
            "name": "put",
            "summary": "",
            "url": "classes/Twitch-Http-Http.html#method_put"
        },                {
            "fqsen": "\\Twitch\\Http\\Http\u003A\u003Apatch\u0028\u0029",
            "name": "patch",
            "summary": "",
            "url": "classes/Twitch-Http-Http.html#method_patch"
        },                {
            "fqsen": "\\Twitch\\Http\\Http\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/Twitch-Http-Http.html#method_delete"
        },                {
            "fqsen": "\\Twitch\\Http\\Http\u003A\u003Arequest\u0028\u0029",
            "name": "request",
            "summary": "",
            "url": "classes/Twitch-Http-Http.html#method_request"
        },                {
            "fqsen": "\\Twitch\\Http\\Http\u003A\u003Apump\u0028\u0029",
            "name": "pump",
            "summary": "Dispatches\u0020queued\u0020requests\u0020up\u0020to\u0020the\u0020concurrency\u0020ceiling.",
            "url": "classes/Twitch-Http-Http.html#method_pump"
        },                {
            "fqsen": "\\Twitch\\Http\\Http\u003A\u003Asend\u0028\u0029",
            "name": "send",
            "summary": "",
            "url": "classes/Twitch-Http-Http.html#method_send"
        },                {
            "fqsen": "\\Twitch\\Http\\Http\u003A\u003AhandleResponse\u0028\u0029",
            "name": "handleResponse",
            "summary": "",
            "url": "classes/Twitch-Http-Http.html#method_handleResponse"
        },                {
            "fqsen": "\\Twitch\\Http\\Http\u003A\u003Aretry\u0028\u0029",
            "name": "retry",
            "summary": "",
            "url": "classes/Twitch-Http-Http.html#method_retry"
        },                {
            "fqsen": "\\Twitch\\Http\\Http\u003A\u003AVERSION",
            "name": "VERSION",
            "summary": "",
            "url": "classes/Twitch-Http-Http.html#constant_VERSION"
        },                {
            "fqsen": "\\Twitch\\Http\\Http\u003A\u003ABASE_URL",
            "name": "BASE_URL",
            "summary": "Helix\u0020API\u0020base.\u0020OAuth\u0020lives\u0020on\u0020a\u0020different\u0020host\u0020\u2014\u0020see\u0020\u007B\u0040see\u0020OAuth\u007D.",
            "url": "classes/Twitch-Http-Http.html#constant_BASE_URL"
        },                {
            "fqsen": "\\Twitch\\Http\\Http\u003A\u003ACONCURRENT_REQUESTS",
            "name": "CONCURRENT_REQUESTS",
            "summary": "In\u002Dflight\u0020request\u0020ceiling.",
            "url": "classes/Twitch-Http-Http.html#constant_CONCURRENT_REQUESTS"
        },                {
            "fqsen": "\\Twitch\\Http\\Http\u003A\u003AMAX_ATTEMPTS",
            "name": "MAX_ATTEMPTS",
            "summary": "Give\u0020up\u0020after\u0020this\u0020many\u0020attempts\u0020at\u0020one\u0020request.",
            "url": "classes/Twitch-Http-Http.html#constant_MAX_ATTEMPTS"
        },                {
            "fqsen": "\\Twitch\\Http\\Http\u003A\u003A\u0024driver",
            "name": "driver",
            "summary": "",
            "url": "classes/Twitch-Http-Http.html#property_driver"
        },                {
            "fqsen": "\\Twitch\\Http\\Http\u003A\u003A\u0024logger",
            "name": "logger",
            "summary": "",
            "url": "classes/Twitch-Http-Http.html#property_logger"
        },                {
            "fqsen": "\\Twitch\\Http\\Http\u003A\u003A\u0024queue",
            "name": "queue",
            "summary": "",
            "url": "classes/Twitch-Http-Http.html#property_queue"
        },                {
            "fqsen": "\\Twitch\\Http\\Http\u003A\u003A\u0024inFlight",
            "name": "inFlight",
            "summary": "",
            "url": "classes/Twitch-Http-Http.html#property_inFlight"
        },                {
            "fqsen": "\\Twitch\\Http\\Http\u003A\u003A\u0024rateLimit",
            "name": "rateLimit",
            "summary": "",
            "url": "classes/Twitch-Http-Http.html#property_rateLimit"
        },                {
            "fqsen": "\\Twitch\\Http\\Http\u003A\u003A\u0024throttled",
            "name": "throttled",
            "summary": "Set\u0020while\u0020the\u0020client\u0020is\u0020holding\u0020for\u0020the\u0020bucket\u0020to\u0020refill.",
            "url": "classes/Twitch-Http-Http.html#property_throttled"
        },                {
            "fqsen": "\\Twitch\\Http\\Http\u003A\u003A\u0024token",
            "name": "token",
            "summary": "",
            "url": "classes/Twitch-Http-Http.html#property_token"
        },                {
            "fqsen": "\\Twitch\\Http\\Http\u003A\u003A\u0024clientId",
            "name": "clientId",
            "summary": "",
            "url": "classes/Twitch-Http-Http.html#property_clientId"
        },                {
            "fqsen": "\\Twitch\\Http\\Http\u003A\u003A\u0024loop",
            "name": "loop",
            "summary": "",
            "url": "classes/Twitch-Http-Http.html#property_loop"
        },                {
            "fqsen": "\\Twitch\\Http\\HttpInterface",
            "name": "HttpInterface",
            "summary": "The\u0020contract\u0020\u007B\u0040see\u0020Http\u007D\u0020fulfils.\u0020Depend\u0020on\u0020this\u0020rather\u0020than\u0020the\u0020concrete\nclass\u0020so\u0020the\u0020transport\u0020can\u0020be\u0020decorated\u0020or\u0020faked\u0020\u0028auth\u002Drefresh\u0020wrappers,\ntest\u0020doubles,\u0020alternative\u0020drivers\u0029.",
            "url": "classes/Twitch-Http-HttpInterface.html"
        },                {
            "fqsen": "\\Twitch\\Http\\HttpInterface\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "",
            "url": "classes/Twitch-Http-HttpInterface.html#method_get"
        },                {
            "fqsen": "\\Twitch\\Http\\HttpInterface\u003A\u003Apost\u0028\u0029",
            "name": "post",
            "summary": "",
            "url": "classes/Twitch-Http-HttpInterface.html#method_post"
        },                {
            "fqsen": "\\Twitch\\Http\\HttpInterface\u003A\u003Aput\u0028\u0029",
            "name": "put",
            "summary": "",
            "url": "classes/Twitch-Http-HttpInterface.html#method_put"
        },                {
            "fqsen": "\\Twitch\\Http\\HttpInterface\u003A\u003Apatch\u0028\u0029",
            "name": "patch",
            "summary": "",
            "url": "classes/Twitch-Http-HttpInterface.html#method_patch"
        },                {
            "fqsen": "\\Twitch\\Http\\HttpInterface\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/Twitch-Http-HttpInterface.html#method_delete"
        },                {
            "fqsen": "\\Twitch\\Http\\HttpInterface\u003A\u003Arequest\u0028\u0029",
            "name": "request",
            "summary": "",
            "url": "classes/Twitch-Http-HttpInterface.html#method_request"
        },                {
            "fqsen": "\\Twitch\\Http\\HttpInterface\u003A\u003AsetToken\u0028\u0029",
            "name": "setToken",
            "summary": "Swap\u0020in\u0020a\u0020fresh\u0020OAuth\u0020token\u0020\u0028e.g.\u0020after\u0020a\u0020refresh\u0029.",
            "url": "classes/Twitch-Http-HttpInterface.html#method_setToken"
        },                {
            "fqsen": "\\Twitch\\Http\\HttpInterface\u003A\u003AgetRateLimit\u0028\u0029",
            "name": "getRateLimit",
            "summary": "The\u0020most\u0020recent\u0020rate\u002Dlimit\u0020bucket\u0020snapshot,\u0020if\u0020any\u0020request\u0020has\u0020completed.",
            "url": "classes/Twitch-Http-HttpInterface.html#method_getRateLimit"
        },                {
            "fqsen": "\\Twitch\\Http\\OAuth",
            "name": "OAuth",
            "summary": "Thin\u0020async\u0020wrapper\u0020around\u0020the\u0020Twitch\u0020OAuth2\u0020endpoints\u0020on\u0020\u0060id.twitch.tv\u0060.",
            "url": "classes/Twitch-Http-OAuth.html"
        },                {
            "fqsen": "\\Twitch\\Http\\OAuth\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Twitch-Http-OAuth.html#method___construct"
        },                {
            "fqsen": "\\Twitch\\Http\\OAuth\u003A\u003AclientCredentials\u0028\u0029",
            "name": "clientCredentials",
            "summary": "App\u0020access\u0020token\u0020via\u0020the\u0020client\u002Dcredentials\u0020grant.",
            "url": "classes/Twitch-Http-OAuth.html#method_clientCredentials"
        },                {
            "fqsen": "\\Twitch\\Http\\OAuth\u003A\u003AauthorizeUrl\u0028\u0029",
            "name": "authorizeUrl",
            "summary": "The\u0020URL\u0020to\u0020send\u0020a\u0020user\u0020to\u0020so\u0020they\u0020can\u0020authorize\u0020the\u0020application.",
            "url": "classes/Twitch-Http-OAuth.html#method_authorizeUrl"
        },                {
            "fqsen": "\\Twitch\\Http\\OAuth\u003A\u003AexchangeCode\u0028\u0029",
            "name": "exchangeCode",
            "summary": "Trade\u0020an\u0020authorization\u0020code\u0020for\u0020a\u0020user\u0020access\u0020\u002B\u0020refresh\u0020token.",
            "url": "classes/Twitch-Http-OAuth.html#method_exchangeCode"
        },                {
            "fqsen": "\\Twitch\\Http\\OAuth\u003A\u003ArefreshToken\u0028\u0029",
            "name": "refreshToken",
            "summary": "",
            "url": "classes/Twitch-Http-OAuth.html#method_refreshToken"
        },                {
            "fqsen": "\\Twitch\\Http\\OAuth\u003A\u003AdeviceCode\u0028\u0029",
            "name": "deviceCode",
            "summary": "Start\u0020the\u0020device\u002Dcode\u0020flow.",
            "url": "classes/Twitch-Http-OAuth.html#method_deviceCode"
        },                {
            "fqsen": "\\Twitch\\Http\\OAuth\u003A\u003ApollDeviceToken\u0028\u0029",
            "name": "pollDeviceToken",
            "summary": "Exchange\u0020a\u0020device\u0020code\u0020for\u0020a\u0020token.\u0020Rejects\u0020with\u0020a\u0020\u007B\u0040see\u0020HttpException\u007D\ncarrying\u0020\u0060authorization_pending\u0060\u0020until\u0020the\u0020user\u0020completes\u0020the\u0020flow.",
            "url": "classes/Twitch-Http-OAuth.html#method_pollDeviceToken"
        },                {
            "fqsen": "\\Twitch\\Http\\OAuth\u003A\u003Avalidate\u0028\u0029",
            "name": "validate",
            "summary": "Validate\u0020a\u0020token.\u0020Rejects\u0020with\u0020\u007B\u0040see\u0020InvalidTokenException\u007D\u0020when\u0020expired.",
            "url": "classes/Twitch-Http-OAuth.html#method_validate"
        },                {
            "fqsen": "\\Twitch\\Http\\OAuth\u003A\u003Arevoke\u0028\u0029",
            "name": "revoke",
            "summary": "",
            "url": "classes/Twitch-Http-OAuth.html#method_revoke"
        },                {
            "fqsen": "\\Twitch\\Http\\OAuth\u003A\u003Atoken\u0028\u0029",
            "name": "token",
            "summary": "",
            "url": "classes/Twitch-Http-OAuth.html#method_token"
        },                {
            "fqsen": "\\Twitch\\Http\\OAuth\u003A\u003Aform\u0028\u0029",
            "name": "form",
            "summary": "",
            "url": "classes/Twitch-Http-OAuth.html#method_form"
        },                {
            "fqsen": "\\Twitch\\Http\\OAuth\u003A\u003Adecode\u0028\u0029",
            "name": "decode",
            "summary": "",
            "url": "classes/Twitch-Http-OAuth.html#method_decode"
        },                {
            "fqsen": "\\Twitch\\Http\\OAuth\u003A\u003ABASE",
            "name": "BASE",
            "summary": "",
            "url": "classes/Twitch-Http-OAuth.html#constant_BASE"
        },                {
            "fqsen": "\\Twitch\\Http\\OAuth\u003A\u003A\u0024browser",
            "name": "browser",
            "summary": "",
            "url": "classes/Twitch-Http-OAuth.html#property_browser"
        },                {
            "fqsen": "\\Twitch\\Http\\OAuth\u003A\u003A\u0024clientId",
            "name": "clientId",
            "summary": "",
            "url": "classes/Twitch-Http-OAuth.html#property_clientId"
        },                {
            "fqsen": "\\Twitch\\Http\\OAuth\u003A\u003A\u0024clientSecret",
            "name": "clientSecret",
            "summary": "",
            "url": "classes/Twitch-Http-OAuth.html#property_clientSecret"
        },                {
            "fqsen": "\\Twitch\\Http\\RateLimit",
            "name": "RateLimit",
            "summary": "A\u0020snapshot\u0020of\u0020the\u0020Twitch\u0020rate\u002Dlimit\u0020bucket,\u0020read\u0020from\u0020the\u0020\u0060Ratelimit\u002D\u002A\u0060\nresponse\u0020headers.",
            "url": "classes/Twitch-Http-RateLimit.html"
        },                {
            "fqsen": "\\Twitch\\Http\\RateLimit\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Twitch-Http-RateLimit.html#method___construct"
        },                {
            "fqsen": "\\Twitch\\Http\\RateLimit\u003A\u003AfromResponse\u0028\u0029",
            "name": "fromResponse",
            "summary": "",
            "url": "classes/Twitch-Http-RateLimit.html#method_fromResponse"
        },                {
            "fqsen": "\\Twitch\\Http\\RateLimit\u003A\u003AisExhausted\u0028\u0029",
            "name": "isExhausted",
            "summary": "Whether\u0020the\u0020bucket\u0020is\u0020empty\u0020and\u0020callers\u0020should\u0020hold\u0020until\u0020\u007B\u0040see\u0020resetAt\u007D.",
            "url": "classes/Twitch-Http-RateLimit.html#method_isExhausted"
        },                {
            "fqsen": "\\Twitch\\Http\\RateLimit\u003A\u003AretryAfter\u0028\u0029",
            "name": "retryAfter",
            "summary": "Seconds\u0020to\u0020wait\u0020before\u0020the\u0020bucket\u0020refills\u0020\u0028never\u0020negative\u0029.",
            "url": "classes/Twitch-Http-RateLimit.html#method_retryAfter"
        },                {
            "fqsen": "\\Twitch\\Http\\RateLimit\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/Twitch-Http-RateLimit.html#method___toString"
        },                {
            "fqsen": "\\Twitch\\Http\\RateLimit\u003A\u003A\u0024limit",
            "name": "limit",
            "summary": "",
            "url": "classes/Twitch-Http-RateLimit.html#property_limit"
        },                {
            "fqsen": "\\Twitch\\Http\\RateLimit\u003A\u003A\u0024remaining",
            "name": "remaining",
            "summary": "",
            "url": "classes/Twitch-Http-RateLimit.html#property_remaining"
        },                {
            "fqsen": "\\Twitch\\Http\\RateLimit\u003A\u003A\u0024resetAt",
            "name": "resetAt",
            "summary": "",
            "url": "classes/Twitch-Http-RateLimit.html#property_resetAt"
        },                {
            "fqsen": "\\Twitch\\Http\\Request",
            "name": "Request",
            "summary": "One\u0020prepared\u0020HTTP\u0020call\u003A\u0020method,\u0020\u007B\u0040see\u0020Endpoint\u007D,\u0020body,\u0020headers,\u0020and\u0020the\n\u007B\u0040see\u0020Deferred\u007D\u0020that\u0020\u007B\u0040see\u0020Http\u007D\u0020settles\u0020with\u0020the\u0020decoded\u0020payload.",
            "url": "classes/Twitch-Http-Request.html"
        },                {
            "fqsen": "\\Twitch\\Http\\Request\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Twitch-Http-Request.html#method___construct"
        },                {
            "fqsen": "\\Twitch\\Http\\Request\u003A\u003AgetMethod\u0028\u0029",
            "name": "getMethod",
            "summary": "",
            "url": "classes/Twitch-Http-Request.html#method_getMethod"
        },                {
            "fqsen": "\\Twitch\\Http\\Request\u003A\u003AgetEndpoint\u0028\u0029",
            "name": "getEndpoint",
            "summary": "",
            "url": "classes/Twitch-Http-Request.html#method_getEndpoint"
        },                {
            "fqsen": "\\Twitch\\Http\\Request\u003A\u003AgetUrl\u0028\u0029",
            "name": "getUrl",
            "summary": "The\u0020absolute\u0020URL,\u0020base\u0020\u002B\u0020rendered\u0020endpoint\u0020\u002B\u0020query\u0020string.",
            "url": "classes/Twitch-Http-Request.html#method_getUrl"
        },                {
            "fqsen": "\\Twitch\\Http\\Request\u003A\u003AgetContent\u0028\u0029",
            "name": "getContent",
            "summary": "",
            "url": "classes/Twitch-Http-Request.html#method_getContent"
        },                {
            "fqsen": "\\Twitch\\Http\\Request\u003A\u003AgetHeaders\u0028\u0029",
            "name": "getHeaders",
            "summary": "",
            "url": "classes/Twitch-Http-Request.html#method_getHeaders"
        },                {
            "fqsen": "\\Twitch\\Http\\Request\u003A\u003AsetHeader\u0028\u0029",
            "name": "setHeader",
            "summary": "",
            "url": "classes/Twitch-Http-Request.html#method_setHeader"
        },                {
            "fqsen": "\\Twitch\\Http\\Request\u003A\u003AgetDeferred\u0028\u0029",
            "name": "getDeferred",
            "summary": "",
            "url": "classes/Twitch-Http-Request.html#method_getDeferred"
        },                {
            "fqsen": "\\Twitch\\Http\\Request\u003A\u003AbumpAttempts\u0028\u0029",
            "name": "bumpAttempts",
            "summary": "",
            "url": "classes/Twitch-Http-Request.html#method_bumpAttempts"
        },                {
            "fqsen": "\\Twitch\\Http\\Request\u003A\u003AgetAttempts\u0028\u0029",
            "name": "getAttempts",
            "summary": "",
            "url": "classes/Twitch-Http-Request.html#method_getAttempts"
        },                {
            "fqsen": "\\Twitch\\Http\\Request\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/Twitch-Http-Request.html#method___toString"
        },                {
            "fqsen": "\\Twitch\\Http\\Request\u003A\u003A\u0024attempts",
            "name": "attempts",
            "summary": "",
            "url": "classes/Twitch-Http-Request.html#property_attempts"
        },                {
            "fqsen": "\\Twitch\\Http\\Request\u003A\u003A\u0024deferred",
            "name": "deferred",
            "summary": "",
            "url": "classes/Twitch-Http-Request.html#property_deferred"
        },                {
            "fqsen": "\\Twitch\\Http\\Request\u003A\u003A\u0024method",
            "name": "method",
            "summary": "",
            "url": "classes/Twitch-Http-Request.html#property_method"
        },                {
            "fqsen": "\\Twitch\\Http\\Request\u003A\u003A\u0024endpoint",
            "name": "endpoint",
            "summary": "",
            "url": "classes/Twitch-Http-Request.html#property_endpoint"
        },                {
            "fqsen": "\\Twitch\\Http\\Request\u003A\u003A\u0024content",
            "name": "content",
            "summary": "",
            "url": "classes/Twitch-Http-Request.html#property_content"
        },                {
            "fqsen": "\\Twitch\\Http\\Request\u003A\u003A\u0024headers",
            "name": "headers",
            "summary": "",
            "url": "classes/Twitch-Http-Request.html#property_headers"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Twitch\\Http",
            "name": "Http",
            "summary": "",
            "url": "namespaces/twitch-http.html"
        },                {
            "fqsen": "\\Twitch",
            "name": "Twitch",
            "summary": "",
            "url": "namespaces/twitch.html"
        },                {
            "fqsen": "\\Twitch\\Http\\Drivers",
            "name": "Drivers",
            "summary": "",
            "url": "namespaces/twitch-http-drivers.html"
        },                {
            "fqsen": "\\Twitch\\Http\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/twitch-http-exceptions.html"
        }            ]
);
